export const NAME = 'Dindim'
export const TITLE = 'We make goods for a better future'
export const DESCRIPTION = 'Tu tienda online de comercio justo para comprar ropa sostenible.'
export const LOGO_SQUARE_PATH = '/static/logo-square.png'
export const SITE_URL = 'https://dindim.es/'
export const EMAIL = 'info@dindim.es'
